// src/pages/Analytics.jsx
// AI Skill Analytics, Demand/Supply Metrics, and Market Insights

import { useState, useEffect } from 'react';
import api from '../api/axios';
import toast from 'react-hot-toast';
import { TrendingUp, Sparkles, BarChart2, Flame, Award, Lightbulb, Users, CheckCircle } from 'lucide-react';

export default function Analytics() {
  const [data, setData]       = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchAnalytics();
  }, []);

  const fetchAnalytics = async () => {
    try {
      const res = await api.get('/analytics/insights');
      setData(res.data);
    } catch {
      toast.error('Failed to load analytics');
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return <div className="page" style={{ textAlign: 'center', paddingTop: '5rem' }}><div className="spinner" /></div>;
  }

  if (!data) return <div className="page" style={{ textAlign: 'center', paddingTop: '5rem' }}>Failed to load insights</div>;

  return (
    <div className="page">
      <div className="container">
        {/* Header */}
        <div style={{ marginBottom: '2rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.375rem' }}>
            <Sparkles size={20} color="var(--color-primary2)" />
            <span style={{ fontSize: '0.8125rem', fontWeight: 700, color: 'var(--color-primary2)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Skill Market Intelligence</span>
          </div>
          <h1 style={{ fontSize: '1.875rem', fontWeight: 800 }}>SkillSwap AI Analytics & Insights</h1>
          <p style={{ color: 'var(--color-muted)', fontSize: '0.9375rem' }}>
            Platform skill supply vs demand trends and AI-driven career recommendations.
          </p>
        </div>

        {/* Quick Stats Grid */}
        <div className="grid grid-3" style={{ marginBottom: '2rem' }}>
          <div className="stat-card">
            <div className="stat-icon" style={{ background: 'rgba(124, 58, 237, 0.15)', color: 'var(--color-primary2)' }}>
              <Users size={22} />
            </div>
            <div className="stat-label">Active Learners</div>
            <div className="stat-value">{data.totalUsers}</div>
          </div>
          <div className="stat-card">
            <div className="stat-icon" style={{ background: 'rgba(16, 185, 129, 0.15)', color: 'var(--color-success)' }}>
              <CheckCircle size={22} />
            </div>
            <div className="stat-label">Completed Swaps</div>
            <div className="stat-value">{data.completedMatches}</div>
          </div>
          <div className="stat-card">
            <div className="stat-icon" style={{ background: 'rgba(245, 158, 11, 0.15)', color: 'var(--color-warning)' }}>
              <Flame size={22} />
            </div>
            <div className="stat-label">Highest Gap Skill</div>
            <div className="stat-value" style={{ fontSize: '1.25rem' }}>{data.skillGaps[0]?.skill || 'Web Design'}</div>
          </div>
        </div>

        {/* AI Recommendations Section */}
        <div className="glass" style={{ padding: '1.75rem', marginBottom: '2rem', borderLeft: '4px solid var(--color-primary2)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.625rem', marginBottom: '1.25rem' }}>
            <Lightbulb size={24} color="var(--color-primary2)" />
            <div>
              <h2 style={{ fontSize: '1.125rem', fontWeight: 800 }}>Personalized AI Skill Recommendations</h2>
              <p style={{ fontSize: '0.8125rem', color: 'var(--color-muted)' }}>Generated by Gemini AI based on your profile and platform trends</p>
            </div>
          </div>

          <div className="grid grid-3" style={{ gap: '1rem' }}>
            {data.aiAdvice?.recommendations?.map((rec, idx) => (
              <div key={idx} style={{ padding: '1.125rem', background: 'var(--color-surface2)', borderRadius: 12, border: '1px solid var(--color-border)' }}>
                <div style={{ fontSize: '0.875rem', fontWeight: 700, color: 'var(--color-primary2)', marginBottom: '0.375rem' }}>
                  {rec.title}
                </div>
                <p style={{ fontSize: '0.8125rem', color: 'var(--color-muted)', lineHeight: 1.5 }}>
                  {rec.advice}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Top Demand & Supply Grid */}
        <div className="grid grid-2" style={{ gap: '1.5rem', marginBottom: '2rem' }}>
          {/* Top In-Demand */}
          <div className="glass" style={{ padding: '1.5rem' }}>
            <h2 style={{ fontSize: '1.125rem', fontWeight: 800, marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <TrendingUp size={20} color="var(--color-secondary)" /> Most Wanted Skills
            </h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.875rem' }}>
              {data.topWanted.map((item, idx) => (
                <div key={idx}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.875rem', fontWeight: 600, marginBottom: '0.25rem' }}>
                    <span>{item.skill}</span>
                    <span style={{ color: 'var(--color-muted)' }}>{item.count} requests</span>
                  </div>
                  <div style={{ height: 8, background: 'var(--color-surface2)', borderRadius: 4, overflow: 'hidden' }}>
                    <div style={{
                      height: '100%',
                      width: `${Math.min(100, (item.count / (data.topWanted[0]?.count || 1)) * 100)}%`,
                      background: 'var(--gradient-secondary)',
                      borderRadius: 4
                    }} />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Top Offered */}
          <div className="glass" style={{ padding: '1.5rem' }}>
            <h2 style={{ fontSize: '1.125rem', fontWeight: 800, marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <BarChart2 size={20} color="var(--color-primary2)" /> Most Offered Skills
            </h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.875rem' }}>
              {data.topOffered.map((item, idx) => (
                <div key={idx}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.875rem', fontWeight: 600, marginBottom: '0.25rem' }}>
                    <span>{item.skill}</span>
                    <span style={{ color: 'var(--color-muted)' }}>{item.count} experts</span>
                  </div>
                  <div style={{ height: 8, background: 'var(--color-surface2)', borderRadius: 4, overflow: 'hidden' }}>
                    <div style={{
                      height: '100%',
                      width: `${Math.min(100, (item.count / (data.topOffered[0]?.count || 1)) * 100)}%`,
                      background: 'var(--gradient-primary)',
                      borderRadius: 4
                    }} />
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Skill Gap Analysis Table */}
        <div className="glass" style={{ padding: '1.5rem' }}>
          <h2 style={{ fontSize: '1.125rem', fontWeight: 800, marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Flame size={20} color="var(--color-warning)" /> Skill Gap Opportunity Matrix
          </h2>
          <p style={{ fontSize: '0.875rem', color: 'var(--color-muted)', marginBottom: '1.25rem' }}>
            Skills with high demand but low supply. Offering these skills yields the fastest barter matches!
          </p>

          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.875rem', textAlign: 'left' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid var(--color-border)', color: 'var(--color-muted)' }}>
                  <th style={{ padding: '0.75rem 1rem' }}>Skill Name</th>
                  <th style={{ padding: '0.75rem 1rem' }}>Demand (Wants)</th>
                  <th style={{ padding: '0.75rem 1rem' }}>Supply (Offers)</th>
                  <th style={{ padding: '0.75rem 1rem' }}>Opportunity Level</th>
                </tr>
              </thead>
              <tbody>
                {data.skillGaps.map((item, idx) => (
                  <tr key={idx} style={{ borderBottom: '1px solid var(--color-border)' }}>
                    <td style={{ padding: '0.875rem 1rem', fontWeight: 700 }}>{item.skill}</td>
                    <td style={{ padding: '0.875rem 1rem' }}>{item.demand} users</td>
                    <td style={{ padding: '0.875rem 1rem' }}>{item.supply} users</td>
                    <td style={{ padding: '0.875rem 1rem' }}>
                      <span className="badge badge-proposed" style={{ fontSize: '0.75rem' }}>🔥 High Opportunity</span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
